"""users table

Revision ID: 52331171ef18
Revises: 11012f39c4c8
Create Date: 2023-11-04 19:24:17.389864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52331171ef18'
down_revision = '11012f39c4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_firstName'), ['firstName'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lastName'), ['lastName'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_lastName'))
        batch_op.drop_index(batch_op.f('ix_user_firstName'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
